package com.testgen.github;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.testgen.model.GeneratedTest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.stereotype.Component;
import org.springframework.web.client.HttpServerErrorException;
import org.springframework.web.client.RestClient;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.function.Supplier;

import static com.testgen.util.Constants.GITHUB_RETRY_BACKOFF;
import static com.testgen.util.Constants.TEST_SOURCE_ROOT;

@Component
public class GitHubPrCreator {

    private static final Logger log = LoggerFactory.getLogger(GitHubPrCreator.class);

    private final RestClient gitHubRestClient;
    private final GitHubAppAuthenticator gitHubAppAuthenticator;

    public GitHubPrCreator(RestClient gitHubRestClient, GitHubAppAuthenticator gitHubAppAuthenticator) {
        this.gitHubRestClient = gitHubRestClient;
        this.gitHubAppAuthenticator = gitHubAppAuthenticator;
    }

    public String deliver(PrDeliveryRequest request) {
        TestBranchName branchName = TestBranchName.from(request.sourceBranch());

        createBranch(request, branchName);
        commitTestFile(request, branchName);
        String testPrUrl = openPullRequest(request, branchName);
        postNotificationComment(request, testPrUrl);

        return testPrUrl;
    }

    private void createBranch(PrDeliveryRequest request, TestBranchName branchName) {
        executeWithRetry(() -> gitHubRestClient.post()
                .uri("/repos/{owner}/{repo}/git/refs", request.owner(), request.repo())
                .header(HttpHeaders.AUTHORIZATION, bearerToken())
                .body(new CreateRefRequest("refs/heads/" + branchName.value(), request.sourceBranchSha()))
                .retrieve()
                .toBodilessEntity());
    }

    private void commitTestFile(PrDeliveryRequest request, TestBranchName branchName) {
        GeneratedTest generatedTest = request.generatedTest();
        String path = testFilePath(generatedTest);
        String encodedContent = Base64.getEncoder().encodeToString(generatedTest.testCode().getBytes(StandardCharsets.UTF_8));
        String message = "test: AI-generated tests for PR #" + request.sourcePrNumber();

        executeWithRetry(() -> gitHubRestClient.put()
                .uri("/repos/{owner}/{repo}/contents/" + path, request.owner(), request.repo())
                .header(HttpHeaders.AUTHORIZATION, bearerToken())
                .body(new CommitFileRequest(message, encodedContent, branchName.value()))
                .retrieve()
                .toBodilessEntity());
    }

    private String openPullRequest(PrDeliveryRequest request, TestBranchName branchName) {
        String title = "chore: AI-generated tests for PR #" + request.sourcePrNumber() + " (" + request.sourceBranch() + ")";
        String body = "Generated by AI Test Generation Engine\n\nCovers: " + methodList(request)
                + "\nValidation: " + request.validationStatus();

        PullRequestResponse response = executeWithRetry(() -> gitHubRestClient.post()
                .uri("/repos/{owner}/{repo}/pulls", request.owner(), request.repo())
                .header(HttpHeaders.AUTHORIZATION, bearerToken())
                .body(new CreatePullRequestRequest(title, body, branchName.value(), request.sourceBranch(), false))
                .retrieve()
                .body(PullRequestResponse.class));

        if (response == null || response.htmlUrl() == null) {
            throw new IllegalStateException("GitHub pull request response was empty");
        }
        return response.htmlUrl();
    }

    private void postNotificationComment(PrDeliveryRequest request, String testPrUrl) {
        String commentBody = "🤖 **AI Test Generation Engine** generated tests for the changes in this PR.\n\n"
                + "👉 Review the generated tests: " + testPrUrl + "\n\n"
                + "**Covered methods:** " + methodList(request) + "\n"
                + "**Validation:** " + request.validationStatus();

        executeWithRetry(() -> gitHubRestClient.post()
                .uri("/repos/{owner}/{repo}/issues/{prNumber}/comments",
                        request.owner(), request.repo(), request.sourcePrNumber())
                .header(HttpHeaders.AUTHORIZATION, bearerToken())
                .body(new CreateCommentRequest(commentBody))
                .retrieve()
                .toBodilessEntity());
    }

    private <T> T executeWithRetry(Supplier<T> action) {
        try {
            return action.get();
        } catch (HttpServerErrorException e) {
            log.warn("GitHub API call failed with {}, retrying once after backoff", e.getStatusCode());
            sleepBackoff();
            return action.get();
        }
    }

    private void sleepBackoff() {
        try {
            Thread.sleep(GITHUB_RETRY_BACKOFF.toMillis());
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("Interrupted while retrying GitHub API call", e);
        }
    }

    private String bearerToken() {
        return "Bearer " + gitHubAppAuthenticator.getInstallationToken();
    }

    private String testFilePath(GeneratedTest generatedTest) {
        String packagePath = generatedTest.packageName().replace('.', '/');
        return TEST_SOURCE_ROOT + "/" + packagePath + "/" + generatedTest.className() + ".java";
    }

    private String methodList(PrDeliveryRequest request) {
        return String.join(", ", request.coveredMethods());
    }

    private record CreateRefRequest(String ref, String sha) {}

    private record CommitFileRequest(String message, String content, String branch) {}

    private record CreatePullRequestRequest(String title, String body, String head, String base, boolean draft) {}

    private record CreateCommentRequest(String body) {}

    private record PullRequestResponse(@JsonProperty("html_url") String htmlUrl) {}
}
